// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Skill.Data;
using System;

namespace Skill.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20170912003229_AddSex")]
    partial class AddSex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Skill.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Skill.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Applicable")
                        .IsRequired();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<int>("LabelUseCount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Synopsis")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Lable");
                });

            modelBuilder.Entity("Skill.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<int>("Age");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Hobby")
                        .IsRequired();

                    b.Property<int>("LabelCount");

                    b.Property<int>("LabelUseCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int>("ProjectCount");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Skill.Models.PersonMasterLabel", b =>
                {
                    b.Property<int>("PersonID");

                    b.Property<int>("LabelID");

                    b.HasKey("PersonID", "LabelID");

                    b.HasAlternateKey("LabelID", "PersonID");

                    b.ToTable("PersonMasterLabel");
                });

            modelBuilder.Entity("Skill.Models.PersonUseLabel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LabelID");

                    b.Property<int>("PersonID");

                    b.Property<int>("UseCount");

                    b.Property<DateTime>("UseTime");

                    b.HasKey("ID");

                    b.HasIndex("LabelID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonUseLabel");
                });

            modelBuilder.Entity("Skill.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BeginTime");

                    b.Property<int>("Count");

                    b.Property<int>("CountL");

                    b.Property<string>("FinishTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Skill.Models.ProjectPartakePerson", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("PersonID");

                    b.Property<string>("BeginTime");

                    b.Property<string>("FinishTime");

                    b.HasKey("ProjectID", "PersonID");

                    b.HasAlternateKey("PersonID", "ProjectID");

                    b.ToTable("ProjectPartakePerson");
                });

            modelBuilder.Entity("Skill.Models.ProjectUseLabel", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("LabelID");

                    b.HasKey("ProjectID", "LabelID");

                    b.HasAlternateKey("LabelID", "ProjectID");

                    b.ToTable("ProjectUseLabel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Skill.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Skill.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skill.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Skill.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Skill.Models.PersonMasterLabel", b =>
                {
                    b.HasOne("Skill.Models.Label", "Label")
                        .WithMany("PersonMasterLabel")
                        .HasForeignKey("LabelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skill.Models.Person", "Person")
                        .WithMany("PersonMasterLabel")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Skill.Models.PersonUseLabel", b =>
                {
                    b.HasOne("Skill.Models.Label", "Label")
                        .WithMany("PersonUseLable")
                        .HasForeignKey("LabelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skill.Models.Person", "Person")
                        .WithMany("PersonUserLable")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Skill.Models.ProjectPartakePerson", b =>
                {
                    b.HasOne("Skill.Models.Person", "Person")
                        .WithMany("ProjectPartakePerson")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skill.Models.Project", "Project")
                        .WithMany("ProjectPartakePerson")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Skill.Models.ProjectUseLabel", b =>
                {
                    b.HasOne("Skill.Models.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skill.Models.Project", "Project")
                        .WithMany("ProjectUseLabel")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
